import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { writeSwanctlConf } from '@/lib/pki/strongswan'

// GET - Get VPN configuration
export async function GET() {
  try {
    let config = await db.vpnConfiguration.findFirst()
    
    // Create default config if not exists
    if (!config) {
      config = await db.vpnConfiguration.create({
        data: {}
      })
    }
    
    return NextResponse.json({ config })
  } catch (error) {
    console.error('Get VPN config error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// PUT - Update VPN configuration
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json()
    
    let config = await db.vpnConfiguration.findFirst()
    
    if (!config) {
      config = await db.vpnConfiguration.create({
        data: body
      })
    } else {
      config = await db.vpnConfiguration.update({
        where: { id: config.id },
        data: body
      })
    }
    
    // Log audit
    await db.auditLog.create({
      data: {
        action: 'UPDATE_VPN_CONFIG',
        category: 'VPN_INTEGRATION',
        actorType: 'ADMIN',
        targetType: 'VpnConfiguration',
        details: JSON.stringify(body),
        status: 'SUCCESS',
      },
    })
    
    return NextResponse.json({ config })
  } catch (error) {
    console.error('Update VPN config error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Generate and apply swanctl.conf
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { action } = body
    
    if (action === 'apply') {
      const config = await db.vpnConfiguration.findFirst()
      
      if (!config) {
        return NextResponse.json(
          { error: 'VPN configuration not found' },
          { status: 404 }
        )
      }
      
      // Get CA info
      const ca = await db.certificateAuthority.findFirst({
        where: { isDefault: true, status: 'ACTIVE' }
      })
      
      // Generate swanctl.conf content
      const swanctlContent = generateSwanctlConf(config, ca)
      
      // Write to file
      writeSwanctlConf(swanctlContent)
      
      // Log audit
      await db.auditLog.create({
        data: {
          action: 'APPLY_VPN_CONFIG',
          category: 'VPN_INTEGRATION',
          actorType: 'ADMIN',
          targetType: 'VpnConfiguration',
          details: 'Generated and applied swanctl.conf',
          status: 'SUCCESS',
        },
      })
      
      return NextResponse.json({ 
        success: true, 
        message: 'Configuration applied successfully',
        content: swanctlContent 
      })
    }
    
    if (action === 'preview') {
      const config = await db.vpnConfiguration.findFirst()
      
      if (!config) {
        return NextResponse.json(
          { error: 'VPN configuration not found' },
          { status: 404 }
        )
      }
      
      const ca = await db.certificateAuthority.findFirst({
        where: { isDefault: true, status: 'ACTIVE' }
      })
      
      const swanctlContent = generateSwanctlConf(config, ca)
      
      return NextResponse.json({ content: swanctlContent })
    }
    
    return NextResponse.json(
      { error: 'Invalid action' },
      { status: 400 }
    )
  } catch (error) {
    console.error('Apply VPN config error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// Generate swanctl.conf content from database config
function generateSwanctlConf(config: any, ca: any): string {
  const lines: string[] = []
  
  lines.push('# swanctl.conf - Generated by 24online VPN PKI Management Platform')
  lines.push(`# Generated at: ${new Date().toISOString()}`)
  lines.push('')
  
  // Connections section
  lines.push('connections {')
  lines.push('')
  lines.push(`  ${config.connectionName} {`)
  lines.push('')
  
  // Version
  lines.push(`    version = ${config.ikeVersion}`)
  
  // IKE Proposals
  lines.push(`    proposals = ${config.ikeProposals}`)
  
  // Additional options
  if (config.mobike) {
    lines.push('    mobike = yes')
  }
  if (config.reauthTime !== undefined) {
    lines.push(`    reauth_time = ${config.reauthTime}`)
  }
  if (config.fragmentation) {
    lines.push('    fragmentation = yes')
  }
  
  lines.push('')
  
  // Local section
  lines.push('    local {')
  lines.push(`      auth = ${config.localAuth}`)
  lines.push(`      certs = ${config.localCert}`)
  lines.push(`      id = ${config.localId || 'vpn.server'}`)
  lines.push('    }')
  lines.push('')
  
  // Remote section
  lines.push('    remote {')
  lines.push(`      auth = ${config.remoteAuth}`)
  // Only include ca_id if explicitly configured (it's optional in strongSwan)
  // The ca_id constraint can cause auth failures if it doesn't match the CA subject
  if (config.remoteCaId) {
    lines.push(`      ca_id = "${config.remoteCaId}"`)
  }
  lines.push('    }')
  lines.push('')
  
  // Children section
  lines.push('    children {')
  lines.push('      net {')
  lines.push(`        local_ts = ${config.localTrafficSelector}`)
  lines.push(`        esp_proposals = ${config.espProposals}`)
  lines.push(`        start_action = ${config.startAction}`)
  lines.push('      }')
  lines.push('    }')
  lines.push('')
  
  // Pools
  lines.push(`    pools = ${config.poolName}`)
  lines.push('  }')
  lines.push('')
  lines.push('}')
  lines.push('')
  
  // Pools section
  lines.push('pools {')
  lines.push(`  ${config.poolName} {`)
  lines.push(`    addrs = ${config.poolAddressRange}`)
  lines.push(`    dns = ${config.dnsServers}`)
  lines.push('  }')
  lines.push('}')
  
  return lines.join('\n')
}
