import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import * as fs from 'fs'
import * as path from 'path'
import { execSync } from 'child_process'
import { randomUUID } from 'crypto'
import {
  getPKIPaths,
  ensurePKIDirectories,
} from '@/lib/pki/config'
import {
  ensureStrongSwanDirs,
  STRONGSWAN_PATHS,
} from '@/lib/pki/strongswan'

/**
 * CSR (Certificate Signing Request) Generator API
 * 
 * This API generates CSRs for both server and client certificates.
 * CSRs can be signed by an external CA or by the managed PKI.
 * 
 * Flow:
 * 1. Generate private key: openssl genrsa -out key.pem 4096
 * 2. Generate CSR: openssl req -new -key key.pem -out csr.pem -subj "/CN=xxx" -config <san_config>
 * 
 * Storage:
 * - Keys: /etc/swanctl/private/
 * - CSRs: /etc/swanctl/csr/
 */

// CSR directory path
const CSR_DIR = '/etc/swanctl/csr'

/**
 * Ensure CSR directory exists
 */
function ensureCSRDirectory(): void {
  if (!fs.existsSync(CSR_DIR)) {
    fs.mkdirSync(CSR_DIR, { recursive: true, mode: 0o755 })
  }
}

/**
 * Generate OpenSSL config file for CSR with SANs
 */
function generateCSRConfig(params: {
  sanDomains: string[]
  sanIPs: string[]
}): string {
  const { sanDomains, sanIPs } = params
  const configPath = path.join(CSR_DIR, `san_config_${Date.now()}.cnf`)
  
  // Build SAN entries
  const sanEntries: string[] = []
  let index = 0
  
  // Add DNS SANs
  for (const domain of sanDomains) {
    sanEntries.push(`DNS.${index} = ${domain}`)
    index++
  }
  
  // Add IP SANs
  for (const ip of sanIPs) {
    sanEntries.push(`IP.${index} = ${ip}`)
    index++
  }
  
  const config = `# OpenSSL CSR Configuration with SANs
# Generated by VPN PKI Management Platform

[req]
default_bits = 4096
prompt = no
default_md = sha256
distinguished_name = dn
req_extensions = req_ext

[dn]
CN = will_be_replaced

[req_ext]
subjectAltName = @alt_names

[alt_names]
${sanEntries.join('\n')}
`
  
  fs.writeFileSync(configPath, config, { mode: 0o644 })
  return configPath
}

/**
 * Generate a server CSR
 */
async function generateServerCSR(params: {
  commonName: string
  sanDomains: string[]
  sanIPs: string[]
  keySize: number
  organization?: string
  organizationalUnit?: string
  country?: string
  state?: string
  locality?: string
}): Promise<{ csrId: string; csrPem: string; keyPath: string; csrPath: string }> {
  const { commonName, sanDomains, sanIPs, keySize, organization, organizationalUnit, country, state, locality } = params
  
  // Ensure directories exist
  ensurePKIDirectories()
  ensureStrongSwanDirs()
  ensureCSRDirectory()
  
  // Generate unique ID for this CSR
  const csrId = `server_${commonName.replace(/[^a-zA-Z0-9]/g, '_')}_${Date.now()}`
  const keyPath = path.join(STRONGSWAN_PATHS.privateDir, `${csrId}.key`)
  const csrPath = path.join(CSR_DIR, `${csrId}.csr`)
  
  console.log(`[CSR] Generating server CSR for: ${commonName}`)
  console.log(`[CSR] Key size: ${keySize}`)
  console.log(`[CSR] SANs - Domains: ${sanDomains.join(', ')}, IPs: ${sanIPs.join(', ')}`)
  
  // Step 1: Generate private key using OpenSSL
  console.log('[CSR] Step 1: Generating private key...')
  try {
    execSync(
      `openssl genrsa -out ${keyPath} ${keySize}`,
      { encoding: 'utf-8' }
    )
    fs.chmodSync(keyPath, 0o600)
    console.log(`[CSR] Private key saved to: ${keyPath}`)
  } catch (error) {
    console.error('[CSR] Failed to generate private key:', error)
    throw new Error(`Failed to generate private key: ${error}`)
  }
  
  // Step 2: Build subject DN
  let subject = `/CN=${commonName}`
  if (country) subject = `/C=${country}${subject}`
  if (state) subject = `/ST=${state}${subject}`
  if (locality) subject = `/L=${locality}${subject}`
  if (organization) subject = `/O=${organization}${subject}`
  if (organizationalUnit) subject = `/OU=${organizationalUnit}${subject}`
  
  // Step 3: Generate CSR
  console.log('[CSR] Step 2: Generating CSR...')
  
  // If we have SANs, use a config file
  if (sanDomains.length > 0 || sanIPs.length > 0) {
    // Generate config file with SANs (include CN in SANs for modern clients)
    const allDomains = [commonName, ...sanDomains.filter(d => d !== commonName)]
    const configPath = generateCSRConfig({
      sanDomains: allDomains,
      sanIPs,
    })
    
    // Update the config with the actual CN
    let configContent = fs.readFileSync(configPath, 'utf-8')
    configContent = configContent.replace('CN = will_be_replaced', `CN = ${commonName}`)
    fs.writeFileSync(configPath, configContent)
    
    try {
      execSync(
        `openssl req -new -key ${keyPath} -out ${csrPath} -subj "${subject}" -config ${configPath}`,
        { encoding: 'utf-8' }
      )
      console.log(`[CSR] CSR saved to: ${csrPath}`)
      
      // Clean up config file
      fs.unlinkSync(configPath)
    } catch (error) {
      // Clean up config file on error
      if (fs.existsSync(configPath)) {
        fs.unlinkSync(configPath)
      }
      throw new Error(`Failed to generate CSR: ${error}`)
    }
  } else {
    // No SANs, simple CSR
    try {
      execSync(
        `openssl req -new -key ${keyPath} -out ${csrPath} -subj "${subject}"`,
        { encoding: 'utf-8' }
      )
      console.log(`[CSR] CSR saved to: ${csrPath}`)
    } catch (error) {
      throw new Error(`Failed to generate CSR: ${error}`)
    }
  }
  
  // Read CSR content
  const csrPem = fs.readFileSync(csrPath, 'utf-8')
  
  return { csrId, csrPem, keyPath, csrPath }
}

/**
 * Generate a client CSR
 */
async function generateClientCSR(params: {
  commonName: string
  email?: string
  userId: string
  keySize: number
  organization?: string
  organizationalUnit?: string
  country?: string
  state?: string
  locality?: string
}): Promise<{ csrId: string; csrPem: string; keyPath: string; csrPath: string }> {
  const { commonName, email, userId, keySize, organization, organizationalUnit, country, state, locality } = params
  
  // Ensure directories exist
  ensurePKIDirectories()
  ensureStrongSwanDirs()
  ensureCSRDirectory()
  
  // Generate unique ID for this CSR
  const csrId = `client_${commonName.replace(/[^a-zA-Z0-9]/g, '_')}_${userId}_${Date.now()}`
  const keyPath = path.join(STRONGSWAN_PATHS.privateDir, `${csrId}.key`)
  const csrPath = path.join(CSR_DIR, `${csrId}.csr`)
  
  console.log(`[CSR] Generating client CSR for: ${commonName}`)
  console.log(`[CSR] User ID: ${userId}`)
  console.log(`[CSR] Key size: ${keySize}`)
  
  // Step 1: Generate private key using OpenSSL
  console.log('[CSR] Step 1: Generating private key...')
  try {
    execSync(
      `openssl genrsa -out ${keyPath} ${keySize}`,
      { encoding: 'utf-8' }
    )
    fs.chmodSync(keyPath, 0o600)
    console.log(`[CSR] Private key saved to: ${keyPath}`)
  } catch (error) {
    console.error('[CSR] Failed to generate private key:', error)
    throw new Error(`Failed to generate private key: ${error}`)
  }
  
  // Step 2: Build subject DN
  let subject = `/CN=${commonName}`
  if (email) subject += `/emailAddress=${email}`
  if (country) subject = `/C=${country}${subject}`
  if (state) subject = `/ST=${state}${subject}`
  if (locality) subject = `/L=${locality}${subject}`
  if (organization) subject = `/O=${organization}${subject}`
  if (organizationalUnit) subject = `/OU=${organizationalUnit}${subject}`
  
  // Step 3: Generate CSR (clients typically don't need SANs)
  console.log('[CSR] Step 2: Generating CSR...')
  try {
    execSync(
      `openssl req -new -key ${keyPath} -out ${csrPath} -subj "${subject}"`,
      { encoding: 'utf-8' }
    )
    console.log(`[CSR] CSR saved to: ${csrPath}`)
  } catch (error) {
    throw new Error(`Failed to generate CSR: ${error}`)
  }
  
  // Read CSR content
  const csrPem = fs.readFileSync(csrPath, 'utf-8')
  
  return { csrId, csrPem, keyPath, csrPath }
}

/**
 * GET - List pending CSRs
 * Returns all CSRs that are waiting to be signed
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const type = searchParams.get('type') || 'all' // 'server', 'client', or 'all'
    
    const csrs: Array<{
      id: string
      type: 'server' | 'client'
      commonName: string
      subject: string
      createdAt: Date
      csrPath: string
      keyPath: string
      san?: string[]
      userId?: string
      username?: string
    }> = []
    
    // Get server CSRs with PENDING status
    if (type === 'all' || type === 'server') {
      const serverCSRs = await db.serverCertificate.findMany({
        where: {
          status: 'PENDING',
          csrPath: { not: null },
        },
        orderBy: { createdAt: 'desc' },
      })
      
      for (const csr of serverCSRs) {
        // Check if CSR file still exists
        if (csr.csrPath && fs.existsSync(csr.csrPath)) {
          csrs.push({
            id: csr.id,
            type: 'server',
            commonName: csr.commonName,
            subject: csr.subject,
            createdAt: csr.createdAt,
            csrPath: csr.csrPath,
            keyPath: csr.keyPath || '',
          })
        }
      }
    }
    
    // Get client CSRs with PENDING status
    if (type === 'all' || type === 'client') {
      const clientCSRs = await db.certificate.findMany({
        where: {
          status: 'PENDING',
          csrPath: { not: null },
        },
        include: {
          user: {
            select: { username: true },
          },
        },
        orderBy: { createdAt: 'desc' },
      })
      
      for (const csr of clientCSRs) {
        // Check if CSR file still exists
        if (csr.csrPath && fs.existsSync(csr.csrPath)) {
          csrs.push({
            id: csr.id,
            type: 'client',
            commonName: csr.commonName,
            subject: csr.subject,
            createdAt: csr.createdAt,
            csrPath: csr.csrPath,
            keyPath: csr.keyPath || '',
            userId: csr.userId,
            username: csr.user?.username,
            san: csr.san ? csr.san.split(',') : undefined,
          })
        }
      }
    }
    
    // Get stats
    const stats = {
      total: csrs.length,
      server: csrs.filter(c => c.type === 'server').length,
      client: csrs.filter(c => c.type === 'client').length,
    }
    
    return NextResponse.json({
      success: true,
      csrs,
      stats,
    })
  } catch (error) {
    console.error('List CSRs error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

/**
 * POST - Generate a new CSR
 * Body: { 
 *   type: 'server' | 'client', 
 *   commonName, 
 *   sanDomains?, 
 *   sanIPs?, 
 *   userId?, 
 *   keySize?, 
 *   organization?,
 *   organizationalUnit?,
 *   country?,
 *   state?,
 *   locality?,
 *   email?
 * }
 */
export async function POST(request: NextRequest) {
  try {
    // Check if OpenSSL is available
    try {
      execSync('which openssl', { encoding: 'utf-8' })
    } catch {
      return NextResponse.json(
        { error: 'OpenSSL is not available. Please install OpenSSL.' },
        { status: 500 }
      )
    }
    
    const body = await request.json()
    const {
      type,
      commonName,
      sanDomains = [],
      sanIPs = [],
      userId,
      keySize = 4096,
      organization,
      organizationalUnit,
      country,
      state,
      locality,
      email,
    } = body
    
    // Validate required fields
    if (!type || !['server', 'client'].includes(type)) {
      return NextResponse.json(
        { error: 'Type must be either "server" or "client"' },
        { status: 400 }
      )
    }
    
    if (!commonName) {
      return NextResponse.json(
        { error: 'Common Name (CN) is required' },
        { status: 400 }
      )
    }
    
    // For client CSR, userId is required
    if (type === 'client' && !userId) {
      return NextResponse.json(
        { error: 'User ID is required for client CSR' },
        { status: 400 }
      )
    }
    
    // Get PKI configuration for default values
    const config = await db.pkiConfiguration.findFirst()
    const size = keySize || config?.minKeySize || 4096
    
    let result: { csrId: string; csrPem: string; keyPath: string; csrPath: string }
    let dbRecord: any
    
    if (type === 'server') {
      // Generate server CSR
      result = await generateServerCSR({
        commonName,
        sanDomains,
        sanIPs,
        keySize: size,
        organization,
        organizationalUnit,
        country,
        state,
        locality,
      })
      
      // Create database record for server CSR
      dbRecord = await db.serverCertificate.create({
        data: {
          hostname: commonName,
          commonName,
          subject: `CN=${commonName}`,
          issuer: '', // Will be filled when signed
          serialNumber: `pending_${Date.now()}`,
          issueDate: new Date(),
          expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000), // Placeholder
          status: 'PENDING',
          keyPath: result.keyPath,
          csrPath: result.csrPath,
          isDeployed: false,
        },
      })
      
      // Log audit
      await db.auditLog.create({
        data: {
          action: 'GENERATE_SERVER_CSR',
          category: 'CERTIFICATE_OPERATIONS',
          actorType: 'ADMIN',
          targetId: dbRecord.id,
          targetType: 'ServerCertificate',
          details: JSON.stringify({
            commonName,
            keySize: size,
            sanDomains,
            sanIPs,
            csrPath: result.csrPath,
            keyPath: result.keyPath,
          }),
          status: 'SUCCESS',
        },
      })
    } else {
      // Verify user exists
      const user = await db.vpnUser.findUnique({
        where: { id: userId },
      })
      
      if (!user) {
        return NextResponse.json(
          { error: 'User not found' },
          { status: 404 }
        )
      }
      
      // Use user's full name or username as commonName if not provided
      const cn = commonName || user.fullName || user.username
      const userEmail = email || user.email
      
      // Generate client CSR
      result = await generateClientCSR({
        commonName: cn,
        email: userEmail,
        userId: userId!,
        keySize: size,
        organization,
        organizationalUnit,
        country,
        state,
        locality,
      })
      
      // Create database record for client CSR
      dbRecord = await db.certificate.create({
        data: {
          userId: userId!,
          serialNumber: `pending_${Date.now()}`,
          commonName: cn,
          subject: `CN=${cn}${userEmail ? `, E=${userEmail}` : ''}`,
          issuer: '', // Will be filled when signed
          issueDate: new Date(),
          expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000), // Placeholder
          status: 'PENDING',
          keyPath: result.keyPath,
          csrPath: result.csrPath,
          keySize: size,
          signatureAlgorithm: 'SHA256',
          certificateType: 'CLIENT',
          ekus: 'clientAuth',
        },
      })
      
      // Log audit
      await db.auditLog.create({
        data: {
          action: 'GENERATE_CLIENT_CSR',
          category: 'CERTIFICATE_OPERATIONS',
          actorType: 'ADMIN',
          targetId: dbRecord.id,
          targetType: 'Certificate',
          details: JSON.stringify({
            userId,
            username: user.username,
            commonName: cn,
            keySize: size,
            csrPath: result.csrPath,
            keyPath: result.keyPath,
          }),
          status: 'SUCCESS',
        },
      })
    }
    
    console.log(`[CSR] Successfully generated ${type} CSR: ${result.csrId}`)
    
    return NextResponse.json({
      success: true,
      csrId: result.csrId,
      dbId: dbRecord.id,
      csrPem: result.csrPem,
      keyPath: result.keyPath,
      csrPath: result.csrPath,
      type,
      commonName,
      download: {
        csr: `/api/csr/${dbRecord.id}/download?type=${type}`,
      },
    })
  } catch (error) {
    console.error('Generate CSR error:', error)
    
    // Log failed attempt
    try {
      await db.auditLog.create({
        data: {
          action: 'GENERATE_CSR_FAILED',
          category: 'CERTIFICATE_OPERATIONS',
          actorType: 'ADMIN',
          details: JSON.stringify({
            error: error instanceof Error ? error.message : 'Unknown error',
          }),
          status: 'FAILURE',
        },
      })
    } catch (logError) {
      console.error('Failed to log audit:', logError)
    }
    
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Internal server error' },
      { status: 500 }
    )
  }
}
